SELECT
e.SALARY,
d.DEPARTMENT_NAME,
l.city,
r.REGION_NAME,
c.COUNTRY_NAME
from HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d on d.DEPARTMENT_ID = e.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS l on l.LOCATION_ID = d.LOCATION_ID
LEFT JOIN HR.COUNTRIES c ON c.COUNTRY_ID = l.COUNTRY_ID
LEFT JOIN HR.REGIONS r on r.REGION_ID = c.REGION_ID
WHERE SALARY > 0 AND DEPARTMENT_NAME IS NOT NULL and r.REGION_ID IS NOT NULL
;