SELECT
e.EMPLOYEE_ID,
e.FIRST_NAME,
e.LAST_NAME,
e.SALARY,
d.DEPARTMENT_NAME,
j.JOB_TITLE
from HR.EMPLOYEES e
LEFT join HR.DEPARTMENTS d on d.DEPARTMENT_ID = e.DEPARTMENT_ID
LEFT JOIN HR.JOBS j on j.JOB_ID = e.JOB_ID
WHERE SALARY > 0 AND DEPARTMENT_NAME IS NOT NULL
;
